-- 変換対象のテーブルとカラム名を管理するテーブル
CREATE TABLE CONV_TARGET_COLUMN_TBL
(
    TABLE_NAME      VARCHAR2(128) NOT NULL,
    COLUMN_NAME     VARCHAR2(128) NOT NULL,
    CONV_FLG        CHAR(1) NOT NULL,
    CONSTRAINT PK_CONV_TARGET_COLUMN_TBL PRIMARY KEY(TABLE_NAME, COLUMN_NAME)
) TABLESPACE CAREER;

COMMENT ON TABLE CONV_TARGET_COLUMN_TBL IS '変換対象カラム管理テーブル';

COMMENT ON COLUMN CONV_TARGET_COLUMN_TBL.TABLE_NAME IS 'テーブル名';

COMMENT ON COLUMN CONV_TARGET_COLUMN_TBL.COLUMN_NAME IS 'カラム名';

COMMENT ON COLUMN CONV_TARGET_COLUMN_TBL.CONV_FLG IS '変換可否（0:しない、1:する）';


-- データ
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'CJS_JINJI_KENGEN', 'PERSON_ID', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'CJS_NINSYOU', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L01_KAMOKU_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L01_KAMOKU_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L02_CLASS_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L02_CLASS_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L03_CATEGORY1_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L03_CATEGORY1_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L04_CATEGORY2_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L04_CATEGORY2_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L05_CATEGORY3_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L05_CATEGORY3_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L06_CATEGORY4_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L06_CATEGORY4_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L07_CATEGORY5_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L07_CATEGORY5_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L08_KANRIMOTO_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L08_KANRIMOTO_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L09_CHIKU_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L09_CHIKU_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L10_KYOSITU_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L10_KYOSITU_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L11_KOUSI_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L11_KOUSI_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L12_TAISYOSYOKUSYU_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L12_TAISYOSYOKUSYU_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L13_TAISYOSOSIKI_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L13_TAISYOSOSIKI_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L14_TAISYOSYA_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L14_TAISYOSYA_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L14_TAISYOSYA_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L15_MOUSIKOMI_JYOKYO_TBL', 'DOWNLOADSYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L15_MOUSIKOMI_JYOKYO_TBL', 'HANTEISYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L15_MOUSIKOMI_JYOKYO_TBL', 'HOUKOKUSYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L15_MOUSIKOMI_JYOKYO_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L15_MOUSIKOMI_JYOKYO_TBL', 'MOUSIKOMISYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L15_MOUSIKOMI_JYOKYO_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L15_MOUSIKOMI_JYOKYO_TBL', 'SYONINSYA1', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L15_MOUSIKOMI_JYOKYO_TBL', 'SYONINSYA2', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L15_MOUSIKOMI_JYOKYO_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L15_MOUSIKOMI_JYOKYO_TBL', 'UKETUKESYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L16_SYONINSYA_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L16_SYONINSYA_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L16_SYONINSYA_TBL', 'SYONINSYA1', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L16_SYONINSYA_TBL', 'SYONINSYA2', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L16_SYONINSYA_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L17_DAIKONYURYOKU_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L17_DAIKONYURYOKU_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L17_DAIKONYURYOKU_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L51_KYOIKU_TBL', 'DOWNLOADSYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L51_KYOIKU_TBL', 'HANTEISYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L51_KYOIKU_TBL', 'HOUKOKUSYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L51_KYOIKU_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L51_KYOIKU_TBL', 'MOUSIKOMISYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L51_KYOIKU_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L51_KYOIKU_TBL', 'SYONINSYA1', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L51_KYOIKU_TBL', 'SYONINSYA2', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L51_KYOIKU_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L51_KYOIKU_TBL', 'UKETUKESYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L52_LEARNING_OSIRASE_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L52_LEARNING_OSIRASE_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L53_BUMON_IKUSEI_TBL', 'KOUSINSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L53_BUMON_IKUSEI_TBL', 'TOUROKUSYA', '0' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L54_W_SASIMODOSI_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L55_W_TORIKESI_UKETUKE_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L56_USER_DEFAULT_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L81_TYOKUGO_ENQUETE_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L82_FOLLOW_ENQUETE_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L91_ACCESS_LOG_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L92_ES_NINSYO_RIREKI_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L93_CLASS_CYOSEI_TBL', 'MOUSIKOMISYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L93_CLASS_CYOSEI_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L93_CLASS_CYOSEI_TBL', 'SYONINSYA1', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L93_CLASS_CYOSEI_TBL', 'SYONINSYA2', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L93_CLASS_CYOSEI_TBL', 'SYORISYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L93_CLASS_CYOSEI_TBL', 'UKETUKESYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L94_MOUSIKOMI_DEL_RIREKI_TBL', 'MOUSIKOMISYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L94_MOUSIKOMI_DEL_RIREKI_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L94_MOUSIKOMI_DEL_RIREKI_TBL', 'SYONINSYA1', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L94_MOUSIKOMI_DEL_RIREKI_TBL', 'SYONINSYA2', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L94_MOUSIKOMI_DEL_RIREKI_TBL', 'SYORISYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'L94_MOUSIKOMI_DEL_RIREKI_TBL', 'UKETUKESYA', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'PERSONAL_PROFILE_IMPORT', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'PERSONAL_PROFILE_IMPORT', 'SIMEI_NO_FLG', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T01_PERSONAL_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T01_PERSONAL_TBL', 'SIMEI_NO_FLG', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T03_SKILL_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T04_SYOKUMU_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T05_KYOIKU_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T06_SIKAKU_MENKYO_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T07_HYOSYO_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T08_RONBUN_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T10_SYAGAI_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T12_GAKUREKI_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T13_ZEN_SYOKUREKI_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T14_SYANAIREKI_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T32_KAO_SYASIN_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T41_SKILL_YOSO_KANRI_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T50_ACCESS_LOG_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T61_CAREER_DESIGN_TBL', 'MENDANSYA_SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T61_CAREER_DESIGN_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T62_CD_JINJI_COMMENT_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T80_TANTO_MAIN_CLIENT_TBL', 'SIMEI_NO', '1' );
INSERT INTO CONV_TARGET_COLUMN_TBL VALUES( 'T81_KEIKEN_GYOMU_RYOIKI_TBL', 'SIMEI_NO', '1' );

COMMIT;
