CREATE TABLE CONV_PERSONAL_TBL
(
    OLD_SIMEI_NO        VARCHAR2(10) NOT NULL,
    NEW_SIMEI_NO        VARCHAR2(10) NOT NULL
) TABLESPACE CAREER;


COMMENT ON TABLE CONV_PERSONAL_TBL IS '打替え対象社員情報テーブル';

COMMENT ON COLUMN CONV_PERSONAL_TBL.OLD_SIMEI_NO IS '旧氏名No';

COMMENT ON COLUMN CONV_PERSONAL_TBL.NEW_SIMEI_NO IS '新氏名No';
