SET SERVEROUTPUT ON;
SET VERIFY OFF;

DECLARE
    vSQL            VARCHAR2(1000);
    vREC_CNT        PLS_INTEGER;

    CURSOR curTARGET_TABLES
    IS
        SELECT TABLE_NAME, COLUMN_NAME FROM CONV_TARGET_COLUMN_TBL WHERE CONV_FLG = '1' AND COLUMN_NAME = 'SIMEI_NO';

BEGIN

    FOR recTable IN curTARGET_TABLES LOOP
        vSQL := 'SELECT COUNT(*) FROM ( ';
        vSQL := vSQL || 'SELECT TRIM(SIMEI_NO) AS SIMEI_NO FROM ' || recTable.TABLE_NAME;
        vSQL := vSQL || ' MINUS ';
        vSQL := vSQL || 'SELECT TRIM(T01.SIMEI_NO) AS SIMEI_NO FROM T01_PERSONAL_TBL T01 )';
        
        EXECUTE IMMEDIATE vSQL INTO vREC_CNT;
        
        IF vREC_CNT > 0 THEN
            DBMS_OUTPUT.NEW_LINE;
            DBMS_OUTPUT.PUT_LINE(recTable.TABLE_NAME || 'にT01_PERSONAL_TBLに存在しない社員のレコードが、' || vREC_CNT || '件ありました。');
        END IF;
    END LOOP;

EXCEPTION
    WHEN OTHERS THEN
        IF curTARGET_TABLES%ISOPEN THEN
            CLOSE curTARGET_TABLES;
        END IF;

END;

